// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("rescript-test/src/Test.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var CommandRunner = require("../CommandRunner.bs.js");

var eq = Caml_obj.equal;

Test.test("Runs commands", (function (param) {
        Test.assertion("Valid commands list", undefined, eq, CommandRunner.run([
                  "PLACE 1,2,NORTH",
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "RIGHT",
                  "MOVE",
                  "REPORT"
                ]), [{
                north: 4,
                east: 0,
                facing: /* North */0
              }]);
        Test.assertion("Empty commands list", undefined, eq, CommandRunner.run([]), []);
        Test.assertion("Commands with an unimportant invalid command", undefined, eq, CommandRunner.run([
                  "PLACE 1,2,NORTH",
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "SPIN AND TWIRL",
                  "MOVE",
                  "REPORT"
                ]), [{
                north: 3,
                east: 0,
                facing: /* West */1
              }]);
        Test.assertion("Commands with PLACE command later in the list", undefined, eq, CommandRunner.run([
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "PLACE 1,2,NORTH",
                  "RIGHT",
                  "MOVE",
                  "REPORT"
                ]), [{
                north: 2,
                east: 2,
                facing: /* East */3
              }]);
        Test.assertion("Commands with duplicate PLACE and REPORT commands", undefined, eq, CommandRunner.run([
                  "PLACE 1,2,NORTH",
                  "PLACE 1,2,NORTH",
                  "MOVE",
                  "LEFT",
                  "REPORT",
                  "MOVE",
                  "SPIN AND TWIRL",
                  "MOVE",
                  "REPORT"
                ]), [
              {
                north: 3,
                east: 1,
                facing: /* West */1
              },
              {
                north: 3,
                east: 0,
                facing: /* West */1
              }
            ]);
        Test.assertion("Commands with valid PLACE command following invalid attempts", undefined, eq, CommandRunner.run([
                  "PLACE 1",
                  "PLACE",
                  "PLACE 1,2,3,4",
                  "MOVE",
                  "PLACE 1,2,NORTH",
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "SPIN AND TWIRL",
                  "MOVE",
                  "REPORT"
                ]), [{
                north: 3,
                east: 0,
                facing: /* West */1
              }]);
        Test.assertion("Commands with trailing commands after REPORT", undefined, eq, CommandRunner.run([
                  "PLACE 1,2,NORTH",
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "RIGHT",
                  "MOVE",
                  "REPORT",
                  "MOVE",
                  "RIGHT",
                  "TWIST AND SHOUT"
                ]), [{
                north: 4,
                east: 0,
                facing: /* North */0
              }]);
        Test.assertion("Commands with missing PLACE command", undefined, eq, CommandRunner.run([
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "RIGHT",
                  "MOVE",
                  "REPORT"
                ]), []);
        Test.assertion("Commands with invalid PLACE argument", undefined, eq, CommandRunner.run([
                  "PLACE 1,SOUTH,NORTH",
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "RIGHT",
                  "MOVE",
                  "REPORT"
                ]), []);
        Test.assertion("Commands including PLACE with too many arguments", undefined, eq, CommandRunner.run([
                  "PLACE 1,2,NORTH,42",
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "RIGHT",
                  "MOVE",
                  "REPORT"
                ]), []);
        Test.assertion("Commands including PLACE with too few arguments", undefined, eq, CommandRunner.run([
                  "PLACE 1",
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "RIGHT",
                  "MOVE",
                  "REPORT"
                ]), []);
        Test.assertion("Commands including PLACE with no arguments", undefined, eq, CommandRunner.run([
                  "PLACE",
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "RIGHT",
                  "MOVE",
                  "REPORT"
                ]), []);
        Test.assertion("Commands with missing REPORT command in the end", undefined, eq, CommandRunner.run([
                  "PLACE 1,2,NORTH",
                  "MOVE",
                  "LEFT",
                  "MOVE",
                  "RIGHT",
                  "MOVE",
                  "MOVE"
                ]), []);
      }));

exports.eq = eq;
/*  Not a pure module */
