// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

function readCommands(fileName) {
  try {
    return {
            TAG: /* Ok */0,
            _0: Fs.readFileSync(fileName).toString().split("\n")
          };
  }
  catch (exn){
    return {
            TAG: /* Error */1,
            _0: "Failed to read commands from " + fileName
          };
  }
}

exports.readCommands = readCommands;
/* fs Not a pure module */
