// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Robot = require("./Robot.bs.js");
var Table = require("./Table.bs.js");

function place(table, north, east, facing) {
  if (Table.isValidPosition(table, north, east)) {
    return {
            TAG: /* Ok */0,
            _0: {
              robot: {
                north: north,
                east: east,
                facing: facing
              },
              table: table
            }
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: "Placement outside bounds"
          };
  }
}

function move(simulation) {
  var movedRobot = Robot.move(simulation.robot);
  return {
          robot: Table.isValidPosition(simulation.table, movedRobot.north, movedRobot.east) ? movedRobot : simulation.robot,
          table: simulation.table
        };
}

function turnLeft(simulation) {
  return {
          robot: Robot.turnLeft(simulation.robot),
          table: simulation.table
        };
}

function turnRight(simulation) {
  return {
          robot: Robot.turnRight(simulation.robot),
          table: simulation.table
        };
}

function report(simulation) {
  return simulation.robot;
}

exports.place = place;
exports.move = move;
exports.turnLeft = turnLeft;
exports.turnRight = turnRight;
exports.report = report;
/* No side effect */
