// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function isValidPosition(table, north, east) {
  if (north >= 0 && north <= table.northBoundary && east >= 0) {
    return east <= table.eastBoundary;
  } else {
    return false;
  }
}

function make(northBoundaryOpt, eastBoundaryOpt, param) {
  var northBoundary = northBoundaryOpt !== undefined ? northBoundaryOpt : 4;
  var eastBoundary = eastBoundaryOpt !== undefined ? eastBoundaryOpt : 4;
  return {
          northBoundary: northBoundary,
          eastBoundary: eastBoundary
        };
}

exports.isValidPosition = isValidPosition;
exports.make = make;
/* No side effect */
